# 쇼핑몰 매출 데이터 분석을 통한 NumPy 기본 연습 문제

이 연습 문제들은 30일 동안의 쇼핑몰 매출 데이터를 분석하며, NumPy의 기본 기능을 실습하는 것을 목표로 합니다.


### 문제 1: 매출 데이터에서 일일 평균 매출 계산하기
- **설명**: 30일 동안의 쇼핑몰 매출 데이터를 배열로 제공할 때, 일일 평균 매출을 계산하세요.
- **힌트**: `np.mean()` 함수를 사용하여 배열의 평균값을 계산합니다.


In [1]:
import numpy as np
sales_data = np.array([2200, 2350, 2500, 2750, 3000, 3100, 2700, 2600, 2900, 3200,
                       3400, 3600, 3300, 3100, 2900, 2700, 2800, 2900, 3100, 3200,
                       3300, 3400, 3500, 3700, 3600, 3500, 3400, 3300, 3000, 3100])


In [2]:
sales_data.shape

(30,)

In [6]:
# numpy 함수
avg_sales = np.mean(sales_data)
print(avg_sales)
# 행렬의 합 / 행렬의 요소수
avg_sales1 = sales_data.sum() / sales_data.size
print(avg_sales1)

3070.0
3070.0


### 문제 2: 매출 데이터에서 최대 매출일과 최소 매출일 찾기
- **설명**: 매출 데이터에서 가장 높은 매출과 가장 낮은 매출을 기록한 날짜를 찾아보세요.
- **힌트**: `np.argmax()`, `np.argmin()`을 사용하여 최대값, 최소값의 인덱스를 찾습니다.


In [8]:
#sales_data.shape
max_day, min_day = sales_data.argmax(), sales_data.argmin()
print(f'최대 매출일 : {max_day+1}    최소 매출일 : {min_day+1}')

최대 매출일 : 24    최소 매출일 : 1


### 문제 3: 7일 단위로 매출 합계 계산하기
- **설명**: 30일 매출 데이터를 7일 단위로 나누어 각 주차별 매출 합계를 계산하세요.
- **힌트**: 배열을 슬라이싱하거나 `reshape()`를 사용하여 배열을 변환합니다.


In [10]:
sales_data[:28].reshape(4,7)


array([[2200, 2350, 2500, 2750, 3000, 3100, 2700],
       [2600, 2900, 3200, 3400, 3600, 3300, 3100],
       [2900, 2700, 2800, 2900, 3100, 3200, 3300],
       [3400, 3500, 3700, 3600, 3500, 3400, 3300]])

In [14]:
weekly_data = np.pad(sales_data, (0,5), 'constant', constant_values=0).reshape(5,7)
weekly_data

array([[2200, 2350, 2500, 2750, 3000, 3100, 2700],
       [2600, 2900, 3200, 3400, 3600, 3300, 3100],
       [2900, 2700, 2800, 2900, 3100, 3200, 3300],
       [3400, 3500, 3700, 3600, 3500, 3400, 3300],
       [3000, 3100,    0,    0,    0,    0,    0]])

In [18]:
weekly_data.sum(axis=0) #요일별 합계
weekly_data.sum(axis=1) #주별 합계


array([18600, 22100, 20900, 24400,  6100])

### 문제 4: 매출 데이터에서 특정 조건에 맞는 매출 데이터 필터링하기
- **설명**: 매출이 3000 이상인 날들의 매출만 필터링하여 보여주세요.
- **힌트**: 배열에서 조건 필터링을 사용하는 방법을 익힙니다.


In [25]:
#filter()
high_sales = list(filter(lambda x: x>=3000, sales_data))
np.array(high_sales)

array([3000, 3100, 3200, 3400, 3600, 3300, 3100, 3100, 3200, 3300, 3400,
       3500, 3700, 3600, 3500, 3400, 3300, 3000, 3100])

In [27]:
#부울인덱싱
high_sales = sales_data[sales_data>=3000]
high_sales

array([3000, 3100, 3200, 3400, 3600, 3300, 3100, 3100, 3200, 3300, 3400,
       3500, 3700, 3600, 3500, 3400, 3300, 3000, 3100])

### 문제 5: 특정 범위 내 매출의 평균값 계산하기
- **설명**: 매출이 2800에서 3500 사이인 날들의 평균 매출을 계산하세요.
- **힌트**: 조건 필터링 후 `np.mean()`을 사용하여 계산합니다.


# 주차별 평균 계산

# 매출의 중앙값

# 매출이 증가한 날, 감소한 날 카운트

# 각 주차별로 가장 매출이 높았던 날 찾기